version: '3'

services:
  mongodb:
    image: mongo:latest  # Or specify a specific version like 'mongo:6.0'
    restart: always      # Restart policy for service
    ports:
      - 27017:27017      # Map container port to host port 
    volumes:
      - mongodb_data:/data/db  # Persist data

  ui-service:
    build: ./breve-ui
    ports:
      - "3000:80"  # React's typical dev port
    depends_on:
      - url-ingester-service  # Example - Client may depend on backend services 
      - url-shortner-service  # Example - Client may depend on backend services 

  url-ingester-service:
    build: ./breve-ms/breve-url-ingester-service
    ports:
      - "8081:8080"
    depends_on:
      - mongodb

  url-shortner-service:
    build: ./breve-ms/breve-url-shortner-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      
volumes:
  mongodb_data:  
