name: Build Breve UI & Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy whenever there's a push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for accessing the GitHub Pages API

    steps:
      - uses: actions/checkout@v3

      - name: Build breve-ui
        run: | # Replace with your actual build commands
          cd breve-ui
          npm install 
          npm run build

      - name: Deploy
        uses: actions/deploy-pages@v1
