name: Build Breve UI & Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy whenever there's a push to the main branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for accessing the GitHub Pages API
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build breve-ui
        run: | # Replace with your actual build commands
          cd breve-ui
          npm install 
          npm run build
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: breve-ui-build  
          path: breve-ui/build

  download-and-deploy:
    needs: build-and-upload # Ensure the deploy job runs after the build job
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: breve-ui-build 

      - name: Deploy 
        uses: actions/deploy-pages@v1  # Adjust if your build output is in a different location 